version: "3.1"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG.PASSWORD}
      POSTGRES_USER: ${PG.USER}
      POSTGRES_DB: ${PG.DB}
    ports:
      - ${PG.PORT}:${PG.PORT}
